# Generated by Django 4.1.7 on 2023-05-01 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Microbe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("MicrobePhylum", models.CharField(max_length=100)),
                ("MicrobeClass", models.CharField(max_length=100)),
                ("MicrobeOrder", models.CharField(max_length=100)),
                ("MicrobeFamily", models.CharField(max_length=100)),
                ("MicrobeGenus", models.CharField(max_length=100)),
                ("MicrobeSpecies", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(max_length=2, null=True),
                ),
                ("birthdate", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MicrobePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("title", models.CharField(max_length=200)),
                ("longitude", models.DecimalField(decimal_places=3, max_digits=6)),
                ("latitude", models.DecimalField(decimal_places=3, max_digits=5)),
                ("image", models.ImageField(upload_to="")),
                ("thumbnail", models.ImageField(upload_to="")),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "microbe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MyBacteriaSite.microbe",
                    ),
                ),
            ],
        ),
    ]
