# Generated by Django 4.1.7 on 2023-05-03 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MyBacteriaSite", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="microbepost",
            name="thumbnail",
        ),
    ]
