# Generated by Django 4.1.7 on 2023-05-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MyBacteriaSite", "0002_remove_microbepost_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="microbepost",
            name="last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
