# Generated by Django 4.1.7 on 2023-05-04 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MyBacteriaSite", "0005_alter_microbepost_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="microbepost",
            name="likes",
            field=models.ManyToManyField(
                related_name="post_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
