# Generated by Django 4.1.7 on 2023-05-05 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("MyBacteriaSite", "0006_microbepost_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microbepost",
            name="likes",
            field=models.ManyToManyField(
                null=True, related_name="post_like", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
