# Generated by Django 4.1.7 on 2023-05-06 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MyBacteriaSite", "0008_alter_microbepost_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microbepost",
            name="microbe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MyBacteriaSite.microbe",
            ),
        ),
    ]
